export default {
  LOGIN: 'LOGIN_API',
  CLEAR_LOGIN: 'CLEAR_LOGIN_API',
  SEND_OTP: 'SEND_OTP',
  CLEAR_SEND_OTP: 'CLEAR_SEND_OTP',
  VERIFY_OTP: 'VERIFY_OTP',
  CLEAR_VERIFY_OTP: 'CLEAR_VERIFY_OTP',
  FORGET_PASSWORD_VERIFY_EMAIL: 'FORGET_PASSWORD_VERIFY_EMAIL',
  CLEAR_FORGET_PASSWORD_VERIFY_EMAIL: 'CLEAR_FORGET_PASSWORD_VERIFY_EMAIL',
  DUMMY: 'DUMMY',
  CLEAR_DUMMY: 'CLEAR_DUMMY',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CLEAR_RESET_PASSWORD: 'CLEAR_RESET_PASSWORD',
  EMAIL_VERIFY_FORGOT_PASSWORD: 'EMAIL_VERIFY_FORGOT_PASSWORD',
  CLEAR_EMAIL_VERIFY_FORGOT_PASSWORD: 'CLEAR_EMAIL_VERIFY_FORGOT_PASSWORD',
  OTP_VERIFICATION_FORGOT_PASSWORD: 'OTP_VERIFICATION_FORGOT_PASSWORD',
  CLEAR_OTP_VERIFICATION_FORGOT_PASSWORD: 'CLEAR_OTP_VERIFICATION_FORGOT_PASSWORD',
  SEND_OTP_SIGNUP: 'SEND_OTP_SIGNUP',
  CLEAR_SEND_OTP_SIGNUP: 'CLEAR_SEND_OTP_SIGNUP',
  VERIFY_OTP_SIGNUP: 'VERIFY_OTP_SIGNUP',
  CLEAR_VERIFY_OTP_SIGNUP: 'CLEAR_VERIFY_OTP_SIGNUP',
  GET_ALL_STATES: 'GET_ALL_STATES',
  CLEAR_GET_ALL_STATES: 'CLEAR_GET_ALL_STATES',
  GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
  CLEAR_GET_ALL_COUNTRIES: 'CLEAR_GET_ALL_COUNTRIES',
  GET_ALL_DISTRICTS: 'GET_ALL_DISTRICTS',
  CLEAR_GET_ALL_DISTRICTS: 'CLEAR_GET_ALL_DISTRICTS`',
  GET_ALL_BOARDS: 'GET_ALL_BOARDS',
  CLEAR_GET_ALL_BOARDS: 'CLEAR_GET_ALL_BOARDS',
  GET_ALL_SCHOOLS: 'GET_ALL_SCHOOLS',
  CLEAR_GET_ALL_SCHOOLS: 'CLEAR_GET_ALL_SCHOOLS',
  GET_ALL_GRADE: 'GET_ALL_GRADE',
  CLEAR_GET_ALL_GRADE: 'CLEAR_GET_ALL_GRADE',
  GET_ALL_QUALIFICATIONS: 'GET_ALL_QUALIFICATIONS',
  CLEAR_GET_ALL_QUALIFICATIONS: 'CLEAR_GET_ALL_QUALIFICATIONS',
  GET_ALL_UNIVERSITIES: 'GET_ALL_UNIVERSITIES',
  CLEAR_GET_ALL_UNIVERSITIES: 'CLEAR_GET_ALL_UNIVERSITIES',
  SIGNUP: 'SIGNUP',
  CLEAR_GET_ALL_COUNSELLOR: 'CLEAR_GET_ALL_COUNSELLOR',
  GET_ALL_COUNSELLOR: 'GET_ALL_COUNSELLOR',
  CLEAR_SIGNUP: 'CLEAR_SIGNUP',
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  CLEAR_ADMIN_LOGIN: 'CLEAR_ADMIN_LOGIN',
  ADMIN_FORGOT_PASSWORD: 'ADMIN_FORGOT_PASSWORD',
  CLEAR_ADMIN_FORGOT_PASSWORD: 'CLEAR_ADMIN_FORGOT_PASSWORD',
  ADMIN_RESET_PASSWORD: 'ADMIN_RESET_PASSWORD',
  CLEAR_ADMIN_RESET_PASSWORD: 'CLEAR_ADMIN_RESET_PASSWORD',
  MOBILE_VERIFICATION: 'MOBILE_VERIFICATION',
  CLEAR_MOBILE_VERIFICATION: 'CLEAR_MOBILE_VERIFICATION',
  MOBILE_VERIFICATION_OTP_SEND: 'MOBILE_VERIFICATION_OTP_SEND',
  CLEAR_MOBILE_VERIFICATION_OTP_SEND: 'CLEAR_MOBILE_VERIFICATION_OTP_SEND',
  CENTER_LOGIN: 'CENTER_LOGIN',
  CLEAR_CENTER_LOGIN: 'CLEAR_CENTER_LOGIN',
  CLEAR_CHANGE_PASSWORD: 'CLEAR_CHANGE_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  GET_ALL_CENTERS: 'GET_ALL_CENTERS',
  CLEAR_GET_ALL_CENTERS: 'CLEAR_GET_ALL_CENTERS',

  // admin-dashboard
  CLEAR_GET_ADMIN_DASHBOARD: 'CLEAR_GET_ADMIN_DASHBOARD',
  GET_ADMIN_DASHBOARD: 'GET_ADMIN_DASHBOARD',

  // Grade Management
  ADD_GRADE_DATA: 'ADD_GRADE_DATA',
  CLEAR_ADD_GRADE_DATA: 'CLEAR_ADD_GRADE_DATA',
  GET_ALL_GRADE_DATA: 'GET_ALL_GRADE_DATA',
  CLEAR_GET_ALL_GRADE_DATA: 'CLEAR_GET_ALL_GRADE_DATA',
  GET_SPECIFIC_GRADE: 'GET_SPECIFIC_GRADE',
  CLEAR_GET_SPECIFIC_GRADE: 'CLEAR_GET_SPECIFIC_GRADE',
  EDIT_SPECIFIC_GRADE: 'EDIT_SPECIFIC_GRADE',
  CLEAR_EDIT_SPECIFIC_GRADE: 'CLEAR_EDIT_SPECIFIC_GRADE',
  DELETE_GRADE: 'DELETE_GRADE',
  CLEAR_DELETE_GRADE: 'CLEAR_DELETE_GRADE',
  VIEW_UNIVERSITY_DATA: 'VIEW_UNIVERSITY_DATA',
  CLEAR_VIEW_UNIVERSITY_DATA: 'CLEAR_VIEW_UNIVERSITY_DATA',

  // School Management
  ADD_SCHOOL_DATA: 'ADD_SCHOOL_DATA',
  CLEAR_ADD_SCHOOL_DATA: 'CLEAR_ADD_SCHOOL_DATA',
  GET_ALL_SCHOOL_DATA: 'GET_ALL_SCHOOL_DATA',
  CLEAR_GET_ALL_SCHOOL_DATA: 'CLEAR_GET_ALL_SCHOOL_DATA',
  GET_SPECIFIC_SCHOOL: 'GET_SPECIFIC_SCHOOL',
  CLEAR_GET_SPECIFIC_SCHOOL: 'CLEAR_GET_SPECIFIC_SCHOOL',
  EDIT_SPECIFIC_SCHOOL: 'EDIT_SPECIFIC_SCHOOL',
  CLEAR_EDIT_SPECIFIC_SCHOOL: 'CLEAR_EDIT_SPECIFIC_SCHOOL',
  DELETE_SCHOOL: 'DELETE_SCHOOL',
  CLEAR_DELETE_SCHOOL: 'CLEAR_DELETE_SCHOOL',

  // University Management
  ADD_UNIVERSITY_DATA: 'ADD_UNIVERSITY_DATA',
  CLEAR_ADD_UNIVERSITY_DATA: 'CLEAR_ADD_UNIVERSITY_DATA',
  GET_ALL_UNIVERSITY_DATA: 'GET_ALL_UNIVERSITY_DATA',
  CLEAR_GET_ALL_UNIVERSITY_DATA: 'CLEAR_GET_ALL_UNIVERSITY_DATA',
  GET_SPECIFIC_UNIVERSITY: 'GET_SPECIFIC_UNIVERSITY',
  CLEAR_GET_SPECIFIC_UNIVERSITY: 'CLEAR_GET_SPECIFIC_UNIVERSITY',
  EDIT_SPECIFIC_UNIVERSITY: 'EDIT_SPECIFIC_UNIVERSITY',
  CLEAR_EDIT_SPECIFIC_UNIVERSITY: 'CLEAR_EDIT_SPECIFIC_UNIVERSITY',
  DELETE_UNIVERSITY: 'DELETE_UNIVERSITY',
  CLEAR_DELETE_UNIVERSITY: 'CLEAR_DELETE_UNIVERSITY',

  // CITY Management
  ADD_CITY_DATA: 'ADD_CITY_DATA',
  CLEAR_ADD_CITY_DATA: 'CLEAR_ADD_CITY_DATA',
  GET_ALL_CITY_DATA: 'GET_ALL_CITY_DATA',
  CLEAR_GET_ALL_CITY_DATA: 'CLEAR_GET_ALL_CITY_DATA',
  GET_SPECIFIC_CITY: 'GET_SPECIFIC_CITY',
  CLEAR_GET_SPECIFIC_CITY: 'CLEAR_GET_SPECIFIC_CITY',
  EDIT_SPECIFIC_CITY: 'EDIT_SPECIFIC_CITY',
  CLEAR_EDIT_SPECIFIC_CITY: 'CLEAR_EDIT_SPECIFIC_CITY',
  DELETE_CITY: 'DELETE_CITY',
  CLEAR_DELETE_CITY: 'CLEAR_DELETE_CITY',

  //  SUBADMIN Management
  ADD_SUBADMIN_DATA: 'ADD_SUBADMIN_DATA',
  CLEAR_ADD_SUBADMIN_DATA: 'CLEAR_ADD_SUBADMIN_DATA',
  GET_ALL_SUBADMIN_DATA: 'GET_ALL_SUBADMIN_DATA',
  CLEAR_GET_ALL_SUBADMIN_DATA: 'CLEAR_GET_ALL_SUBADMIN_DATA',
  GET_SPECIFIC_SUBADMIN: 'GET_SPECIFIC_SUBADMIN',
  CLEAR_GET_SPECIFIC_SUBADMIN: 'CLEAR_GET_SPECIFIC_SUBADMIN',
  EDIT_SPECIFIC_SUBADMIN: 'EDIT_SPECIFIC_SUBADMIN',
  CLEAR_EDIT_SPECIFIC_SUBADMIN: 'CLEAR_EDIT_SPECIFIC_SUBADMIN',
  DELETE_SUBADMIN: 'DELETE_SUBADMIN',
  CLEAR_DELETE_SUBADMIN: 'CLEAR_DELETE_SUBADMIN',
  GET_ALL_ROLE_SELECT: 'GET_ALL_ROLE_SELECT',
  CLEAR_GET_ALL_ROLE_SELECT: 'CLEAR_GET_ALL_ROLE_SELECT',

  // STUDENT Management
  CLEAR_EXPORT_STUDENTS: 'CLEAR_EXPORT_STUDENTS',
  EXPORT_STUDENTS: 'EXPORT_STUDENTS',
  CLEAR_ADD_SPECIFIC_CSVFILE: 'CLEAR_ADD_SPECIFIC_CSVFILE',
  ADD_SPECIFIC_CSVFILE: 'ADD_SPECIFIC_CSVFILE',
  ADD_STUDENT_DATA: 'ADD_STUDENT_DATA',
  CLEAR_ADD_STUDENT_DATA: 'CLEAR_ADD_STUDENT_DATA',
  GET_ALL_STUDENT_DATA: 'GET_ALL_STUDENT_DATA',
  CLEAR_GET_ALL_STUDENT_DATA: 'CLEAR_GET_ALL_STUDENT_DATA',
  GET_SPECIFIC_STUDENT: 'GET_SPECIFIC_STUDENT',
  CLEAR_GET_SPECIFIC_STUDENT: 'CLEAR_GET_SPECIFIC_STUDENT',
  EDIT_SPECIFIC_STUDENT: 'EDIT_SPECIFIC_STUDENT',
  CLEAR_EDIT_SPECIFIC_STUDENT: 'CLEAR_EDIT_SPECIFIC_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  CLEAR_DELETE_STUDENT: 'CLEAR_DELETE_STUDENT',
  GENERATE_REPORT: 'GENERATE_REPORT',
  CLEAR_GENERATE_REPORT: 'CLEAR_GENERATE_REPORT',

  // CENTER Management
  EXPORT_CENTERS: 'EXPORT_CENTERS',
  CLEAR_EXPORT_CENTERS: 'CLEAR_EXPORT_CENTERS',
  ADD_CENTER_DATA: 'ADD_CENTER_DATA',
  CLEAR_ADD_CENTER_DATA: 'CLEAR_ADD_CENTER_DATA',
  GET_ALL_CENTER_DATA: 'GET_ALL_CENTER_DATA',
  CLEAR_GET_ALL_CENTER_DATA: 'CLEAR_GET_ALL_CENTER_DATA',
  GET_SPECIFIC_CENTER: 'GET_SPECIFIC_CENTER',
  CLEAR_GET_SPECIFIC_CENTER: 'CLEAR_GET_SPECIFIC_CENTER',
  EDIT_SPECIFIC_CENTER: 'EDIT_SPECIFIC_CENTER',
  CLEAR_EDIT_SPECIFIC_CENTER: 'CLEAR_EDIT_SPECIFIC_CENTER',
  DELETE_CENTER: 'DELETE_STUDENT',
  CLEAR_DELETE_CENTER: 'CLEAR_DELETE_STUDENT',

  // Center csv student
  CLEAR_ADD_SPECIFIC_CSVFILE_CENTER: 'CLEAR_ADD_SPECIFIC_CSVFILE_CENTER',
  ADD_SPECIFIC_CSVFILE_CENTER: 'ADD_SPECIFIC_CSVFILE_CENTER',

  // Cnter Redeem history Request
  CLEAR_GET_REDEEM_HISTORY_CENTER_SUCCESS: 'CLEAR_GET_REDEEM_HISTORY_CENTER_SUCCESS',
  GET_REDEEM_HISTORY_CENTER_SUCCESS: 'GET_REDEEM_HISTORY_CENTER_SUCCESS',
  CLEAR_GET_SPECIFIC_REDEEM_REQ: 'CLEAR_GET_SPECIFIC_REDEEM_REQ',
  GET_SPECIFIC_REDEEM_REQ: 'GET_SPECIFIC_REDEEM_REQ',
  CLEAR_EDIT_SPECIFIC_REDEEM_REQ: 'CLEAR_EDIT_SPECIFIC_REDEEM_REQ',
  EDIT_SPECIFIC_REDEEM_REQ: 'EDIT_SPECIFIC_REDEEM_REQ',
  CLEAR_VIEW_SPECIFIC_REDEEM_REQ: 'CLEAR_VIEW_SPECIFIC_REDEEM_REQ',
  VIEW_SPECIFIC_REDEEM_REQ: 'VIEW_SPECIFIC_REDEEM_REQ',

  // COUNSELLOR Management
  CLEAR_EXPORT_COUNSELLORS: 'CLEAR_EXPORT_COUNSELLORS',
  EXPORT_COUNSELLORS: 'EXPORT_COUNSELLORS',
  ADD_COUNSELLOR_DATA: 'ADD_COUNSELLOR_DATA',
  CLEAR_ADD_COUNSELLOR_DATA: 'CLEAR_ADD_COUNSELLOR_DATA',
  GET_ALL_COUNSELLOR_DATA: 'GET_ALL_COUNSELLOR_DATA',
  CLEAR_GET_ALL_COUNSELLOR_DATA: 'CLEAR_GET_ALL_COUNSELLOR_DATA',
  GET_SPECIFIC_COUNSELLOR: 'GET_SPECIFIC_COUNSELLOR',
  CLEAR_GET_SPECIFIC_COUNSELLOR: 'CLEAR_GET_SPECIFIC_COUNSELLOR',
  EDIT_SPECIFIC_COUNSELLOR: 'EDIT_SPECIFIC_COUNSELLOR',
  CLEAR_EDIT_SPECIFIC_COUNSELLOR: 'CLEAR_EDIT_SPECIFIC_COUNSELLOR',
  DELETE_COUNSELLOR: 'DELETE_COUNSELLOR',
  CLEAR_DELETE_COUNSELLOR: 'CLEAR_DELETE_COUNSELLOR',

  // STATE Management
  ADD_STATE_DATA: 'ADD_STATE_DATA',
  CLEAR_ADD_STATE_DATA: 'CLEAR_ADD_CITY_DATA',
  GET_ALL_STATE_DATA: 'GET_ALL_STATE_DATA',
  CLEAR_GET_ALL_STATE_DATA: 'CLEAR_GET_ALL_STATE_DATA',
  GET_SPECIFIC_STATE: 'GET_SPECIFIC_STATE',
  CLEAR_GET_SPECIFIC_STATE: 'CLEAR_GET_SPECIFIC_STATE',
  EDIT_SPECIFIC_STATE: 'EDIT_SPECIFIC_STATE',
  CLEAR_EDIT_SPECIFIC_STATE: 'CLEAR_EDIT_SPECIFIC_STATE',
  DELETE_STATE: 'DELETE_STATE',
  CLEAR_DELETE_STATE: 'CLEAR_DELETE_STATE',

  // PACKAGE Management
  GET_ALL_PACKAGE_DATA: 'GET_ALL_PACKAGE_DATA',
  CLEAR_GET_ALL_PACKAGE_DATA: 'CLEAR_GET_ALL_PACKAGE_DATA',
  ADD_PACKAGE_DATA: 'ADD_PACKAGE_DATA',
  CLEAR_ADD_PACKAGE_DATA: 'CLEAR_ADD_PACKAGE_DATA',
  GET_SPECIFIC_PACKAGE: 'GET_SPECIFIC_PACKAGE',
  CLEAR_GET_SPECIFIC_PACKAGE: 'CLEAR_GET_SPECIFIC_PACKAGE',
  EDIT_SPECIFIC_PACKAGE: 'EDIT_SPECIFIC_PACKAGE',
  CLEAR_EDIT_SPECIFIC_PACKAGE: 'CLEAR_EDIT_SPECIFIC_PACKAGE',
  DELETE_PACKAGE: 'DELETE_PACKAGE',
  CLEAR_DELETE_PACKAGE: 'CLEAR_DELETE_PACKAGE',

  // Board Management
  ADD_BOARD_DATA: 'ADD_BOARD_DATA',
  CLEAR_ADD_BOARD_DATA: 'CLEAR_ADD_BOARD_DATA',
  GET_ALL_BOARD_DATA: 'GET_ALL_BOARD_DATA',
  CLEAR_GET_ALL_BOARD_DATA: 'CLEAR_GET_ALL_BOARD_DATA',
  GET_SPECIFIC_BOARD: 'GET_SPECIFIC_BOARD',
  CLEAR_GET_SPECIFIC_BOARD: 'CLEAR_GET_SPECIFIC_BOARD',
  EDIT_SPECIFIC_BOARD: 'EDIT_SPECIFIC_BOARD',
  CLEAR_EDIT_SPECIFIC_BOARD: 'CLEAR_EDIT_SPECIFIC_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',
  CLEAR_DELETE_BOARD: 'CLEAR_DELETE_BOARD',

  // Question Management
  ADD_QUESTION_DATA: 'ADD_QUESTION_DATA',
  CLEAR_ADD_QUESTION_DATA: 'CLEAR_ADD_QUESTION_DATA',
  GET_ALL_QUESTION_DATA: 'GET_ALL_QUESTION_DATA',
  CLEAR_GET_ALL_QUESTION_DATA: 'CLEAR_GET_ALL_QUESTION_DATA',
  GET_SPECIFIC_QUESTION: 'GET_SPECIFIC_QUESTION',
  CLEAR_GET_SPECIFIC_QUESTION: 'CLEAR_GET_SPECIFIC_QUESTION',
  EDIT_SPECIFIC_QUESTION: 'EDIT_SPECIFIC_QUESTION',
  CLEAR_EDIT_SPECIFIC_QUESTION: 'CLEAR_EDIT_SPECIFIC_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
  CLEAR_DELETE_QUESTION: 'CLEAR_DELETE_QUESTION',

  // Test Category
  ADD_TEST_SUB_CATEGORY_DATA: 'ADD_TEST_SUB_CATEGORY_DATA',
  CLEAR_ADD_TEST_SUB_CATEGORY_DATA: 'CLEAR_ADD_TEST_SUB_CATEGORY_DATA',

  // Norms Management
  ADD_NORMS_DATA: 'ADD_NORMS_DATA',
  CLEAR_ADD_NORMS_DATA: 'CLEAR_ADD_NORMS_DATA',
  GET_ALL_NORMS_DATA: 'GET_ALL_NORMS_DATA',
  CLEAR_GET_ALL_NORMS_DATA: 'CLEAR_GET_ALL_NORMS_DATA',
  GET_SPECIFIC_NORMS: 'GET_SPECIFIC_NORMS',
  CLEAR_GET_SPECIFIC_NORMS: 'CLEAR_GET_SPECIFIC_NORMS',
  EDIT_SPECIFIC_NORMS: 'EDIT_SPECIFIC_NORMS',
  CLEAR_EDIT_SPECIFIC_NORMS: 'CLEAR_EDIT_SPECIFIC_NORMS',
  DELETE_NORMS: 'DELETE_NORMS',
  CLEAR_DELETE_NORMS: 'CLEAR_DELETE_NORMS',

  // Test Time Norms
  ADD_TEST_TIME_NORMS_DATA: 'ADD_TEST_TIME_NORMS_DATA',
  CLEAR_ADD_TEST_TIME_NORMS_DATA: 'CLEAR_ADD_TEST_TIME_NORMS_DATA',
  GET_ALL_TEST_TIME_NORMS_DATA: 'GET_ALL_TEST_TIME_NORMS_DATA',
  CLEAR_GET_ALL_TEST_TIME_NORMS_DATA: 'CLEAR_GET_ALL_TEST_TIME_NORMS_DATA',
  GET_SPECIFIC_TEST_TIME_NORMS: 'GET_SPECIFIC_TEST_TIME_NORMS',
  CLEAR_GET_SPECIFIC_TEST_TIME_NORMS: 'CLEAR_GET_SPECIFIC_TEST_TIME_NORMS',
  EDIT_SPECIFIC_TEST_TIME_NORMS: 'EDIT_SPECIFIC_TEST_TIME_NORMS',
  CLEAR_EDIT_SPECIFIC_TEST_TIME_NORMS: 'CLEAR_EDIT_SPECIFIC_TEST_TIME_NORMS',
  DELETE_TEST_TIME_NORMS: 'DELETE_TEST_TIME_NORMS',
  CLEAR_DELETE_TEST_TIME_NORMS: 'CLEAR_DELETE_TEST_TIME_NORMS',

  // Test Norms Description
  ADD_TEST_NORMS_DESCRIPTION_DATA: 'ADD_TEST_NORMS_DESCRIPTION_DATA',
  CLEAR_ADD_TEST_NORMS_DESCRIPTION_DATA: 'CLEAR_ADD_TEST_NORMS_DESCRIPTION_DATA',
  GET_ALL_TEST_NORMS_DESCRIPTION_DATA: 'GET_ALL_TEST_NORMS_DESCRIPTION_DATA',
  CLEAR_GET_ALL_TEST_NORMS_DESCRIPTION_DATA: 'CLEAR_GET_ALL_TEST_NORMS_DESCRIPTION_DATA',
  GET_SPECIFIC_TEST_NORMS_DESCRIPTION: 'GET_SPECIFIC_TEST_NORMS_DESCRIPTION',
  CLEAR_GET_SPECIFIC_TEST_NORMS_DESCRIPTION: 'CLEAR_GET_SPECIFIC_TEST_NORMS_DESCRIPTION',
  EDIT_SPECIFIC_TEST_NORMS_DESCRIPTION: 'EDIT_SPECIFIC_TEST_NORMS_DESCRIPTION',
  CLEAR_EDIT_SPECIFIC_TEST_NORMS_DESCRIPTION: 'CLEAR_EDIT_SPECIFIC_TEST_NORMS_DESCRIPTION',
  DELETE_TEST_NORMS_DESCRIPTION: 'DELETE_TEST_NORMS_DESCRIPTION',
  CLEAR_DELETE_TEST_NORMS_DESCRIPTION: 'CLEAR_DELETE_TEST_NORMS_DESCRIPTION',

  // Software Matrix
  ADD_SOFTWARE_METRICS_DATA: 'ADD_SOFTWARE_METRICS_DATA',
  CLEAR_ADD_SOFTWARE_METRICS_DATA: 'CLEAR_ADD_SOFTWARE_METRICS_DATA',
  GET_ALL_SOFTWARE_METRICS_DATA: 'GET_ALL_SOFTWARE_METRICS_DATA',
  CLEAR_GET_ALL_SOFTWARE_METRICS_DATA: 'CLEAR_GET_ALL_SOFTWARE_METRICS_DATA',
  GET_SPECIFIC_SOFTWARE_METRICS: 'GET_SPECIFIC_SOFTWARE_METRICS',
  CLEAR_GET_SPECIFIC_SOFTWARE_METRICS: 'CLEAR_GET_SPECIFIC_SOFTWARE_METRICS',
  EDIT_SPECIFIC_SOFTWARE_METRICS: 'EDIT_SPECIFIC_SOFTWARE_METRICS',
  CLEAR_EDIT_SPECIFIC_SOFTWARE_METRICS: 'CLEAR_EDIT_SPECIFIC_SOFTWARE_METRICS',
  DELETE_SOFTWARE_METRICS: 'DELETE_SOFTWARE_METRICS',
  CLEAR_DELETE_SOFTWARE_METRICS: 'CLEAR_DELETE_SOFTWARE_METRICS',

  // Norms frontend
  GET_ALL_NORMS_DATA_LIST: 'GET_ALL_NORMS_DATA_LIST',
  CLEAR_GET_ALL_NORMS_DATA_LIST: 'CLEAR_GET_ALL_NORMS_DATA_LIST',

  // Qualificiation Management
  ADD_QUALIFICATION_DATA: 'ADD_QUALIFICATION_DATA',
  CLEAR_ADD_QUALIFICATION_DATA: 'CLEAR_ADD_QUALIFICATION_DATA',
  GET_ALL_QUALIFICATIONS_DATA: 'GET_ALL_QUALIFICATIONS_DATA',
  CLEAR_GET_ALL_QUALIFICATIONS_DATA: 'CLEAR_GET_ALL_QUALIFICATIONS_DATA',
  GET_SPECIFIC_QUALIFICATIONS_DATA: 'GET_SPECIFIC_QUALIFICATIONS_DATA',
  CLEAR_GET_SPECIFIC_QUALIFICATIONS_DATA: 'CLEAR_GET_SPECIFIC_QUALIFICATIONS_DATA',
  EDIT_SPECIFIC_QUALIFICATION_DATA: 'EDIT_SPECIFIC_QUALIFICATION_DATA',
  CLEAR_EDIT_SPECIFIC_QUALIFICATION_DATA: 'CLEAR_EDIT_SPECIFIC_QUALIFICATION_DATA',
  DELETE_QUALIFICATION: 'DELETE_QUALIFICATION',
  CLEAR_DELETE_QUALIFICATION: 'CLEAR_DELETE_QUALIFICATION',

  // Test Category
  ADD_TEST_CATEGORY_DATA: 'ADD_TEST_CATEGORY_DATA',
  CLEAR_ADD_TEST_CATEGORY_DATA: 'CLEAR_ADD_TEST_CATEGORY_DATA',
  GET_ALL_TEST_CATEGORY_DATA: 'GET_ALL_TEST_CATEGORY_DATA',
  CLEAR_GET_ALL_TEST_CATEGORY_DATA: 'CLEAR_GET_ALL_TEST_CATEGORY_DATA',
  VIEW_TEST_CATEGORY_DATA: 'VIEW_TEST_CATEGORY_DATA',
  CLEAR_VIEW_TEST_CATEGORY_DATA: 'CLEAR_VIEW_TEST_CATEGORY_DATA',
  EDIT_TEST_CATEGORY_DATA: 'EDIT_TEST_CATEGORY_DATA',
  CLEAR_EDIT_TEST_CATEGORY_DATA: 'CLEAR_EDIT_TEST_CATEGORY_DATA',
  DELETE_TEST_CATEGORY_DATA: 'DELETE_TEST_CATEGORY_DATA',
  CLEAR_DELETE_TEST_CATEGORY_DATA: 'CLEAR_DELETE_TEST_CATEGORY_DATA',

  // SubCategory
  GET_ALL_TEST_SUBCATEGORY_DATA: 'GET_ALL_TEST_SUBCATEGORY_DATA',
  CLEAR_GET_ALL_TEST_SUBCATEGORY_DATA: 'CLEAR_GET_ALL_TEST_SUBCATEGORY_DATA',
  VIEW_TEST_SUBCATEGORY_DATA: 'VIEW_TEST_SUBCATEGORY_DATA',
  CLEAR_VIEW_TEST_SUBCATEGORY_DATA: 'CLEAR_VIEW_TEST_SUBCATEGORY_DATA',
  GET_ALL_CATEGORIES_DATA: 'GET_ALL_CATEGORIES_DATA',
  CLEAR_GET_ALL_CATEGORIES_DATA: 'CLEAR_GET_ALL_CATEGORIES_DATA',
  DELETE_TEST_SUBCATEGORY_DATA: 'DELETE_TEST_SUBCATEGORY_DATA',
  CLEAR_DELETE_TEST_SUBCATEGORY_DATA: 'CLEAR_DELETE_TEST_SUBCATEGORY_DATA',
  ADD_SUBCATEGORY: 'ADD_SUBCATEGORY',
  CLEAR_ADD_SUBCATEGORY: 'CLEAR_ADD_SUBCATEGORY',
  EDIT_TEST_SUBCATEGORY: 'EDIT_TEST_SUBCATEGORY',
  CLEAR_EDIT_TEST_SUBCATEGORY: 'CLEAR_EDIT_TEST_SUBCATEGORY',

  GET_ALL_MAIN_CATEGORIES_DATA: 'GET_ALL_MAIN_CATEGORIES_DATA',
  CLEAR_GET_ALL_MAIN_CATEGORIES_DATA: 'CLEAR_GET_ALL_MAIN_CATEGORIES_DATA',

  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  CLEAR_ADMIN_LOGOUT: 'CLEAR_ADMIN_LOGOUT',

  // Grade Norms
  ADD_GRADE_NORMS_DATA: 'ADD_GRADE_NORMS_DATA',
  CLEAR_ADD_GRADE_NORMS_DATA: 'CLEAR_ADD_GRADE_NORMS_DATA',
  GET_ALL_GRADE_NORMS_DATA: 'GET_ALL_GRADE_NORMS_DATA',
  CLEAR_GET_ALL_GRADE_NORMS_DATA: 'CLEAR_GET_ALL_GRADE_NORMS_DATA',
  GET_SPECIFIC_GRADE_NORMS: 'GET_SPECIFIC_GRADE_NORMS',
  CLEAR_GET_SPECIFIC_GRADE_NORMS: 'CLEAR_GET_SPECIFIC_GRADE_NORMS',
  EDIT_SPECIFIC_GRADE_NORMS: 'EDIT_SPECIFIC_GRADE_NORMS',
  CLEAR_EDIT_SPECIFIC_GRADE_NORMS: 'CLEAR_EDIT_SPECIFIC_GRADE_NORMS',
  DELETE_GRADE_NORMS: 'DELETE_GRADE_NORMS',
  CLEAR_DELETE_GRADE_NORMS: 'CLEAR_DELETE_GRADE_NORMS',

  /* Norms Frontend Data */
  ADD_NORMS_FRONTEND_DATA: 'ADD_NORMS_FRONTEND_DATA',
  CLEAR_ADD_NORMS_FRONTEND_DATA: 'CLEAR_ADD_NORMS_FRONTEND_DATA',

  // Career Profile Frontend
  GET_ALL_CAREER_PROFILE_LIST: 'GET_ALL_CAREER_PROFILE_LIST',
  CLEAR_GET_ALL_CAREER_PROFILE_LIST: 'CLEAR_GET_ALL_CAREER_PROFILE_LIST',
  GET_ALL_CAREER_PROFILE_DATA: 'GET_ALL_CAREER_PROFILE_DATA',
  CLEAR_GET_ALL_CAREER_PROFILE_DATA: 'CLEAR_GET_ALL_CAREER_PROFILE_DATA',
  ADD_CAREER_PROFILE_DATA: 'ADD_CAREER_PROFILE_DATA',
  CLEAR_ADD_CAREER_PROFILE_DATA: 'CLEAR_ADD_CAREER_PROFILE_DATA',
  GET_SPECIFIC_CAREER_PROFILE: 'GET_SPECIFIC_CAREER_PROFILE',
  CLEAR_GET_SPECIFIC_CAREER_PROFILE: 'CLEAR_GET_SPECIFIC_CAREER_PROFILE',
  EDIT_SPECIFIC_CAREER_PROFILE: 'EDIT_SPECIFIC_CAREER_PROFILE',
  CLEAR_EDIT_SPECIFIC_CAREER_PROFILE: 'CLEAR_EDIT_SPECIFIC_CAREER_PROFILE',
  DELETE_CAREER_PROFILE: 'DELETE_CAREER_PROFILE',
  CLEAR_DELETE_CAREER_PROFILE: 'CLEAR_DELETE_CAREER_PROFILE',
  DELETE_CAREER_PROFILE_DETAIL: 'DELETE_CAREER_PROFILE_DETAIL',
  CLEAR_DELETE_CAREER_PROFILE_DETAIL: 'CLEAR_DELETE_CAREER_PROFILE_DETAIL',

  DELETE_SOFTWARE_METRICS_DETAIL: 'DELETE_SOFTWARE_METRICS_DETAIL',
  CLEAR_DELETE_SOFTWARE_METRICS_DETAIL: 'CLEAR_DELETE_SOFTWARE_METRICS_DETAIL',

  // Role Management
  GET_ALL_ROLE: 'GET_ALL_ROLE',
  CLEAR_GET_ALL_ROLE: 'CLEAR_GET_ALL_ROLE',
  ADD_ROLE: 'ADD_ROLE',
  CLEAR_ADD_ROLE: 'CLEAR_ADD_ROLE',
  GET_SPECIFIC_ROLE: 'GET_SPECIFIC_ROLE',
  CLEAR_GET_SPECIFIC_ROLE: 'CLEAR_GET_SPECIFIC_ROLE',
  EDIT_SPECIFIC_ROLE: 'EDIT_SPECIFIC_ROLE',
  CLEAR_EDIT_SPECIFIC_ROLE: 'CLEAR_EDIT_SPECIFIC_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  CLEAR_DELETE_ROLE: 'CLEAR_DELETE_ROLE',

  // Role Module Front-end
  GET_ALL_MODULE: 'GET_ALL_MODULE',
  CLEAR_GET_ALL_MODULE: 'CLEAR_GET_ALL_MODULE',

  // Counsellor Panel
  GET_ALL_COUNSELLOR_LIST: 'GET_ALL_COUNSELLOR_LIST',
  CLEAR_GET_ALL_COUNSELLOR_LIST: 'CLEAR_GET_ALL_COUNSELLOR_LIST',

  GET_ALL_TIMESLOTS: 'GET_ALL_TIMESLOTS',
  CLEAR_GET_ALL_TIMESLOTS: 'CLEAR_GET_ALL_TIMESLOTS',

  SET_AVAILABILITY: 'SET_AVAILABILITY',
  CLEAR_SET_AVAILABILITY: 'CLEAR_SET_AVAILABILITY',

  // Session Admin
  CLEAR_GET_ALL_SESSION_DATA_ADMIN: 'CLEAR_GET_ALL_SESSION_DATA_ADMIN',
  GET_ALL_SESSION_DATA_ADMIN: 'GET_ALL_SESSION_DATA_ADMIN',
  CLEAR_GET_DETAILED_VIEW_SESSION_ADMIN: 'CLEAR_GET_DETAILED_VIEW_SESSION_ADMIN',
  GET_DETAILED_VIEW_SESSION_ADMIN: 'GET_DETAILED_VIEW_SESSION_ADMIN',

  // Coupon code Admin
  CLEAR_GET_ALL_COUPEN_CODE_DATA: 'CLEAR_GET_ALL_COUPEN_CODE_DATA',
  GET_ALL_COUPEN_CODE_DATA: 'GET_ALL_COUPEN_CODE_DATA',
  CLEAR_ADD_COUPON_CODE_DATA: 'CLEAR_ADD_COUPON_CODE_DATA',
  ADD_COUPON_CODE_DATA: 'ADD_COUPON_CODE_DATA',
  CLEAR_EDIT_SPECIFIC_COUPON_CODE_DATA: 'CLEAR_EDIT_SPECIFIC_COUPON_CODE_DATA',
  EDIT_SPECIFIC_COUPON_CODE_DATA: 'EDIT_SPECIFIC_COUPON_CODE_DATA',
  CLEAR_GET_SPECIFIC_COUPON_CODE_DATA: 'CLEAR_GET_SPECIFIC_COUPON_CODE_DATA',
  GET_SPECIFIC_COUPON_CODE_DATA: 'GET_SPECIFIC_COUPON_CODE_DATA',
  CLEAR_DELETE_COUPON_CODE: 'CLEAR_DELETE_COUPON_CODE',
  DELETE_COUPON_CODE: 'DELETE_COUPON_CODE',

  // admin profile
  CLEAR_VIEW_ADMIN_PROFILE: 'CLEAR_VIEW_ADMIN_PROFILE',
  VIEW_ADMIN_PROFILE: 'VIEW_ADMIN_PROFILE',
  CLEAR_UPDATE_ADMIN_PROFILE: 'CLEAR_UPDATE_ADMIN_PROFILE',
  UPDATE_ADMIN_PROFILE: 'UPDATE_ADMIN_PROFILE',

  // center panel
  CLEAR_GET_ALL_CENTER_DASHBOARD_DATA: 'CLEAR_GET_ALL_CENTER_DASHBOARD_DATA',
  GET_ALL_CENTER_DASHBOARD_DATA: 'GET_ALL_CENTER_DASHBOARD_DATA',
  CLEAR_VIEW_CENTER_PROFILE: 'CLEAR_VIEW_CENTER_PROFILE',
  VIEW_CENTER_PROFILE: 'VIEW_CENTER_PROFILE',
  UPDATE_CENTER_PROFILE: 'UPDATE_CENTER_PROFILE',
  CLEAR_UPDATE_CENTER_PROFILE: 'CLEAR_UPDATE_CENTER_PROFILE',

  // students-center
  CLEAR_GET_ALL_STUDENT_DATA_CEN: 'CLEAR_GET_ALL_STUDENT_DATA_CEN',
  GET_ALL_STUDENT_DATA_CEN: 'GET_ALL_STUDENT_DATA_CEN',
  GET_SPECIFIC_STUDENT_CEN: 'GET_SPECIFIC_STUDENT_CEN',
  CLEAR_GET_SPECIFIC_STUDENT_CEN: 'CLEAR_GET_SPECIFIC_STUDENT_CEN',
  CLEAR_DELETE_STUDENT_CEN: 'CLEAR_DELETE_STUDENT_CEN',
  DELETE_STUDENT_CEN: 'DELETE_STUDENT_CEN',
  CLEAR_EDIT_SPECIFIC_STUDENT_CEN: 'CLEAR_EDIT_SPECIFIC_STUDENT_CEN',
  EDIT_SPECIFIC_STUDENT_CEN: 'EDIT_SPECIFIC_STUDENT_CEN',
  CLEAR_ADD_STUDENT_DATA_CEN: 'CLEAR_ADD_STUDENT_DATA_CEN',
  ADD_STUDENT_DATA_CEN: 'ADD_STUDENT_DATA_CEN',
  GET_AVAILABLE_BY_ID: 'GET_AVAILABLE_BY_ID',
  CLEAR_GET_AVAILABLE_BY_ID: 'CLEAR_GET_AVAILABLE_BY_ID',

  // Purchase-license
  CLEAR_GET_ALL_CENTER_CREDITS: 'CLEAR_GET_ALL_CENTER_CREDITS',
  GET_ALL_CENTER_CREDITS: 'GET_ALL_CENTER_CREDITS',
  CLEAR_GET_ALL_CENTER_PACKAGE_DATA: 'CLEAR_GET_ALL_CENTER_PACKAGE_DATA',
  GET_ALL_CENTER_PACKAGE_DATA: 'GET_ALL_CENTER_PACKAGE_DATA',
  CLEAR_PURCHASED_PACKAGE: 'CLEAR_PURCHASED_PACKAGE',
  PURCHASED_PACKAGE: 'PURCHASED_PACKAGE',
  CLEAR_PACKAGE_PURCHASE_SUCCESS: 'CLEAR_PACKAGE_PURCHASE_SUCCESS',
  PACKAGE_PURCHASE_SUCCESS: 'PACKAGE_PURCHASE_SUCCESS',

  // Purchase-package history
  CLEAR_GET_PACKAGE_HISTORY_LIST: 'CLEAR_GET_PACKAGE_HISTORY_LIST',
  GET_PACKAGE_HISTORY_LIST: 'GET_PACKAGE_HISTORY_LIST',

  // Apply coupon
  APPLY_COUPON_SUCCESS: 'APPLY_COUPON_SUCCESS',
  CLEAR_APPLY_COUPON_SUCCESS: 'CLEAR_APPLY_COUPON_SUCCESS',

  //  Revenue center
  CLEAR_GET_REVENUE_SUCCESS: 'CLEAR_GET_REVENUE_SUCCESS',
  GET_REVENUE_SUCCESS: 'GET_REVENUE_SUCCESS',
  CLEAR_GET_REDEEM_HISTORY_SUCCESS: 'CLEAR_GET_REDEEM_HISTORY_SUCCESS',
  GET_REDEEM_HISTORY_SUCCESS: 'GET_REDEEM_HISTORY_SUCCESS',
  CLEAR_REDEEM_REQUEST_SUCCESS: 'CLEAR_REDEEM_REQUEST_SUCCESS',
  REDEEM_REQUEST_SUCCESS: 'REDEEM_REQUEST_SUCCESS',

  GET_ALL_SESSIONS: 'GET_ALL_SESSIONS',
  CLEAR_GET_ALL_SESSIONS: 'CLEAR_GET_ALL_SESSIONS',

  EDIT_AVAILABILITY: 'EDIT_AVAILABILITY',
  CLEAR_EDIT_AVAILABILITY: 'CLEAR_EDIT_AVAILABILITY',

  DELETE_AVAILABILITY: 'DELETE_AVAILABILITY',
  CLEAR_DELETE_AVAILABILITY: 'CLEAR_DELETE_AVAILABILITY',

  ACCEPTREJECTSESSION: 'ACCEPTREJECTSESSION',
  CLEAR_ACCEPTREJECTSESSION: 'CLEAR_ACCEPTREJECTSESSION',

  GET_DETAILED_VIEW_SESSION: 'GET_DETAILED_VIEW_SESSION',
  CLEAR_GET_DETAILED_VIEW_SESSION: 'CLEAR_GET_DETAILED_VIEW_SESSION',

  COUNSELLOR_RESCHEDULE_SESSION: 'COUNSELLOR_RESCHEDULE_SESSION',
  CLEAR_COUNSELLOR_RESCHEDULE_SESSION: 'CLEAR_COUNSELLOR_RESCHEDULE_SESSION',

  COUNSELLOR_CANCEL_SESSION: 'COUNSELLOR_CANCEL_SESSION',
  CLEAR_COUNSELLOR_CANCEL_SESSION: 'CLEAR_COUNSELLOR_CANCEL_SESSION',

  REPORT_SESSION: 'REPORT_SESSION',
  CLEAR_REPORT_SESSION: 'CLEAR_REPORT_SESSION',

  GET_COUNSELLOR_DASHBOARD: 'GET_COUNSELLOR_DASHBOARD',
  CLEAR_GET_COUNSELLOR_DASHBOARD: 'CLEAR_GET_COUNSELLOR_DASHBOARD',

  VIEW_COUNSELLOR_DETAILS: 'VIEW_COUNSELLOR_DETAILS',
  CLEAR_VIEW_COUNSELLOR_DETAILS: 'CLEAR_VIEW_COUNSELLOR_DETAILS',

  COUNSELLOR_CHANGE_PASSWORD: 'COUNSELLOR_CHANGE_PASSWORD',
  CLEAR_COUNSELLOR_CHANGE_PASSWORD: 'CLEAR_COUNSELLOR_CHANGE_PASSWORD',

  COUNSELLOR_DOWNLOAD_REPORT: 'COUNSELLOR_DOWNLOAD_REPORT',
  CLEAR_COUNSELLOR_DOWNLOAD_REPORT: 'CLEAR_COUNSELLOR_DOWNLOAD_REPORT',

  GET_ISSUE_CATEGORY: 'GET_ISSUE_CATEGORY',
  CLEAR_GET_ISSUE_CATEGORY: 'CLEAR_GET_ISSUE_CATEGORY',

  SUPPORT: 'SUPPORT',
  CLEAR_SUPPORT: 'CLEAR_SUPPORT',

  EDIT_COUNSELLOR_PROFILE: 'EDIT_COUNSELLOR_PROFILE',
  CLEAR_EDIT_COUNSELLOR_PROFILE: 'CLEAR_EDIT_COUNSELLOR_PROFILE',

  COMPLETED_SESSION: 'COMPLETED_SESSION',
  CLEAR_COMPLETED_SESSION: 'CLEAR_COMPLETED_SESSION',

  GET_ALL_SLOTS_DATA: 'GET_ALL_SLOTS_DATA',
  CLEAR_GET_ALL_SLOTS_DATA: 'CLEAR_GET_ALL_SLOTS_DATA'

}
